apiVersion: v1
kind: Service
metadata: 
  name: redis-service
  labels:
    name: redis-service
    app: demo-voting-app
spec:
  ports:
    port: 80
    targetPort: 80
  selector:
    name: redis-pod
    app: demo-voting-app