apiVersion: v1
kind: Service
metadata:
  name: voting-app-service
  labels:
    name: voting-app-service
    app: demo-voting-app
spec:
  ports:
  - port: 6379
    targetPort: 6379

  selector:
    name: voting-app-pod
    app: demo-voting-app

